# 가짜로 매매할 경우 dryrun의 값을 true로 합니다.
# 실제 매매를 할 경우에는 dryrun의 값을 false로 합니다.
dryrun: true

# 매수할 금액을 얼마로 할 것인지 정합니다.
# 업비트는 최소 매매 금액이 5000원입니다. 5000원 이하로 설정하면 매매가 체결되지 않습니다.
# 또 너무 큰 금액으로 설정하면 매수시에 지정가 매수를 하도록 되어있기 때문에 모두 매수되지 않을 수 있습니다.
# 매도시에는 너무 큰 금액을 매수하게 되면 slippage가 발생해서 손실이 클 수 있습니다.
stakeamount: 10000

# 매수가 허용된 최대 건수 입니다.
maxopentrades: 3

# 매매 신호를 발생시킬 때 사용하는 봉입니다.
# 변동성 돌파 전략은 일봉을 기준으로 하는 것이 보통입니다.
# 분봉을 사용하실 수 있으나 수익을 내기 어려우므로 권하지 않습니다.
# 사용가능한 분봉은 1, 3, 5, 10, 15, 30, 60, 240입니다.
# 일봉 설정의 예
candlesize:
  unit: days
  size:  1
# candlesize:
#   unit: minutes
#   size: 3

# 화이트리스트를 설정하면 그곳에 등록된 코인만을 매매 대상으로 합니다.
# 화이트리스트에 아무것도 없다면 업비트에 상장된 모든 코인을 대상으로 합니다.
# 화이트리스트를 활성화 하려면 맨 앞의 "#"을 삭제하고 원하는 코인을 목록을 수작업으로 입력하면 됩니다.
whitelist:
  # - KRW-BTC
  # - KRW-ETH

# 블랙리스트에 등록된 코인은 매수하지 않습니다.
# 스캠코인이나, 상장폐지가 우려되는 코인을 등록하십시오
blacklist:
  # - KRW-BTC
  # - KRW-ETH

# 가격이 매우 낮은 엽전 코인들은 위험이 큽니다.
# minprice 에 적혀있는 가격 이하의 코인은 매매하지 않도록 걸러냅니다.
# 걸러낼 필요가 없다면 0을 입력하세요
minprice: 100

# telegram으로 매매 신호의 알림을 받을 수 있습니다.
# dryrun으로 딕맨을 구동시에 로보어드바이저로 활용할 수 있습니다. 
# telegram에서 신호를 받으시려면 enabled를 true로 변경하시고
# 봇 토근과 챗아이디를 입력하세요
# 토큰을 받는 방법은
# @BotFather 한테 가서 https://t.me/BotFather 봇을 신청하면 줍니다.
# bot을 만든 다음 봇에게 /start 문자를 보내면 봇이 준비됩니다.
# 챗아이디를 받는 방법은
# https://t.me/get_id_bot 에게  '/my_id' 라는 문자를 보내거나
# https://web.telegram.org/k/#@RawDataBot 에 접속해서
# '/start'를 입력하면 알 수 있습니다.

telegram:
  enabled: false
  token: yourbottokenhere
  chatid: yourchatidhere
